import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from 'src/app/services/auth.service';
import { CartService } from 'src/app/services/cart.service';

@Component({
  selector: 'app-menu-service',
  templateUrl: './menu-service.component.html',
  styleUrls: ['./menu-service.component.css'],
})
export class MenuServiceComponent {
  categories = [
    'Pizza',
    'Burger',
    'Coffee',
    'Tea',
    'Fish',
    'Biryani',
    'Samosa',
    'Pasta',
    'Juice',
    'Donut',
    'Fried Noodle/Rice',
    'Momos',
    'Cake',
    'Rolls',
    'Sandwich',
    'Soup',
    'Ice Cream',
  ];
  selectedCategory = 'Pizza';

  allItems = [
    //========================= PIZZA =============================
    {
      name: 'Cheese Pizza',
      price: 199,
      category: 'Pizza',
      image: 'assets/images/Chesse-pizza.avif',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Pizza',
      price: 179,
      category: 'Pizza',
      image: 'assets/images/veg-piza.avif',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Paneer Pizza',
      price: 229,
      category: 'Pizza',
      image: 'assets/images/panner-pizza.avif',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Deluxe Veggie Pizza.',
      price: 229,
      category: 'Pizza',
      image: 'assets/images/Deluxe-Veggie-Pizza.avif',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Paneer tikka pizza',
      price: 229,
      category: 'Pizza',
      image: 'assets/images/Paneer-tikka-pizza.webp ',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Margherita pizza',
      price: 229,
      category: 'Pizza',
      image: 'assets/images/Margherita-pizza.avif',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Farmhouse Pizza',
      price: 229,
      category: 'Pizza',
      image: 'assets/images/Farmhouse-Pizza.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Greek pizza',
      price: 229,
      category: 'Pizza',
      image: 'assets/images/Greek-pizza.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Chicken Dominator',
      price: 229,
      category: 'Pizza',
      image: 'assets/images/Chicken-Dominator.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Jerk Chicken Pizza',
      price: 229,
      category: 'Pizza',
      image: 'assets/images/Jerk-Chicken-Pizza.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Chicken golden delight',
      price: 229,
      category: 'Pizza',
      image: 'assets/images/Chicken-golden-delight.avif',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Tandoori pizza',
      price: 229,
      category: 'Pizza',
      image: 'assets/images/Tandoori-pizza.webp',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Sicilian pizza',
      price: 229,
      category: 'Pizza',
      image: 'assets/images/Sicilian-pizza.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Meat lovers pizza',
      price: 229,
      category: 'Pizza',
      image: 'assets/images/Meat-lovers-pizza.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Chicken Fiesta',
      price: 229,
      category: 'Pizza',
      image: 'assets/images/Chicken-Fiesta.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Sausage',
      price: 229,
      category: 'Pizza',
      image: 'assets/images/Sausage.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    //========================= BURGER =============================
    {
      name: 'Burger Deluxe',
      price: 149,
      category: 'Burger',
      image: 'assets/images/Burger-Deluxe.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Tofu burger',
      price: 149,
      category: 'Burger',
      image: 'assets/images/Tofu-burger.webp',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Black bean burgers',
      price: 149,
      category: 'Burger',
      image: 'assets/images/Black-bean-burgers.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Chickpea burger',
      price: 149,
      category: 'Burger',
      image: 'assets/images/Chickpea-burger.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Falafel burgers',
      price: 149,
      category: 'Burger',
      image: 'assets/images/Falafel-burgers.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Beetroot burger',
      price: 149,
      category: 'Burger',
      image: 'assets/images/Beetroot-burger.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Green burgers',
      price: 149,
      category: 'Burger',
      image: 'assets/images/Green-burgers.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Quinoa burgers',
      price: 149,
      category: 'Burger',
      image: 'assets/images/Quinoa-burgers.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Shawarma Burger',
      price: 149,
      category: 'Burger',
      image: 'assets/images/Shawarma Burger.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Lamb Burger:',
      price: 149,
      category: 'Burger',
      image: 'assets/images/Lamb-Burger.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Lamb Keema Burger',
      price: 149,
      category: 'Burger',
      image: 'assets/images/Lamb-Keema-Burger.jpeg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Chicken Patty Burger',
      price: 149,
      category: 'Burger',
      image: 'assets/images/Chicken-Patty-Burger.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Chicken Cheese Burge ',
      price: 149,
      category: 'Burger',
      image: 'assets/images/Chicken-Cheese-Burge.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Angus Burger',
      price: 149,
      category: 'Burger',
      image: 'assets/images/Angus-Burger.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'BBQ Beef Burger',
      price: 149,
      category: 'Burger',
      image: 'assets/images/BBQ-Beef-Burger.webp',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Classic Beef Burger',
      price: 149,
      category: 'Burger',
      image: 'assets/images/Classic-Beef-Burger.jpeg',
      type: 'non-veg',
      selectedQty: 1,
    },

    //========================= COFFEE =============================
    {
      name: 'Americano',
      price: 249,
      category: 'Coffee',
      image: 'assets/images/Americano.jpg',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Latte',
      price: 249,
      category: 'Coffee',
      image: 'assets/images/Latte.webp',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Cappuccino',
      price: 249,
      category: 'Coffee',
      image: 'assets/images/Cappuccino.jpeg',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Caffè macchiato',
      price: 249,
      category: 'Coffee',
      image: 'assets/images/Caffè macchiato.avif',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Mocha',
      price: 249,
      category: 'Coffee',
      image: 'assets/images/Mocha.jpg',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Cortado',
      price: 249,
      category: 'Coffee',
      image: 'assets/images/Cortado.jpg',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Espresso',
      price: 249,
      category: 'Coffee',
      image: 'assets/images/Espresso.jpeg',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Flat white',
      price: 249,
      category: 'Coffee',
      image: 'assets/images/Flat white.jpeg',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Affogato',
      price: 249,
      category: 'Coffee',
      image: 'assets/images/Affogato.jpg',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Cold brew',
      price: 249,
      category: 'Coffee',
      image: 'assets/images/Cold brew.webp',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Frappe',
      price: 249,
      category: 'Coffee',
      image: 'assets/images/Frappe.png',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Iced coffee',
      price: 249,
      category: 'Coffee',
      image: 'assets/images/Iced coffee.webp',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Black Coffee',
      price: 249,
      category: 'Coffee',
      image: 'assets/images/Black Coffee.jpg',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Long black',
      price: 249,
      category: 'Coffee',
      image: 'assets/images/Long black.webp',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Galão',
      price: 249,
      category: 'Coffee',
      image: 'assets/images/Galão.jpg',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Espresso con panna',
      price: 249,
      category: 'Coffee',
      image: 'assets/images/Espresso con panna.webp',
      // type: 'veg',
      selectedQty: 1,
    },
    //========================= TEA =============================
    {
      name: 'Black Tea',
      price: 249,
      category: 'Tea',
      image: 'assets/images/Black Tea.webp',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Green Tea ',
      price: 249,
      category: 'Tea',
      image: 'assets/images/Green Tea.webp',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Oolong Tea',
      price: 249,
      category: 'Tea',
      image: 'assets/images/Oolong Tea.jpg',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'White Tea',
      price: 249,
      category: 'Tea',
      image: 'assets/images/White Tea.webp',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Yellow Tea',
      price: 249,
      category: 'Tea',
      image: 'assets/images/Yellow Tea.webp',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Pu-erh Tea',
      price: 249,
      category: 'Tea',
      image: 'assets/images/Pu-erh Tea.webp',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Purple Tea',
      price: 249,
      category: 'Tea',
      image: 'assets/images/Purple Tea.webp',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Chamomile Tea',
      price: 249,
      category: 'Tea',
      image: 'assets/images/Chamomile Tea.webp',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Rooibos Tea',
      price: 249,
      category: 'Tea',
      image: 'assets/images/Rooibos Tea.jpg',
      // type: 'veg',
      selectedQty: 1,
    },

    {
      name: 'Black Tea',
      price: 249,
      category: 'Tea',
      image: 'assets/images/Black Tea.webp',
      // type: 'veg',
      selectedQty: 1,
    },
    //========================= FISH =============================
    {
      name: 'Surmal Fish ',
      price: 479,
      category: 'Fish',
      image: 'assets/images/surmal fish.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Pomfret Fish ',
      price: 679,
      category: 'Fish',
      image: 'assets/images/pomfret fish.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'French Fries Fish ',
      price: 129,
      category: 'Fish',
      image: 'assets/images/french fries fish.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Peri Peri French Fries Fish ',
      price: 149,
      category: 'Fish',
      image: 'assets/images/peri peri french fries fish.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Seer Fish Tawa Fry ',
      price: 399,
      category: 'Fish',
      image: 'assets/images/seer fish tawa fry.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Seer Fish Rava Fry ',
      price: 679,
      category: 'Fish',
      image: 'assets/images/seer fish rava fry.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Pomfresh Thali Fish ',
      price: 679,
      category: 'Fish',
      image: 'assets/images/pomfresh thali fish.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Bangda Thali Fish ',
      price: 679,
      category: 'Fish',
      image: 'assets/images/bangda thali fish.webp',
      type: 'non-veg',
      selectedQty: 1,
    },
    //========================= BIRYANI =============================
    {
      name: 'Veg-Hydrabadi Biryani ',
      price: 320,
      category: 'Biryani',
      image: 'assets/images/veg hudrabadi biryani.avif',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Mushroom Biryani ',
      price: 330,
      category: 'Biryani',
      image: 'assets/images/mushroom biryani.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Panner Biryani ',
      price: 350,
      category: 'Biryani',
      image: 'assets/images/Panner biryani.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Kaju Biryani ',
      price: 380,
      category: 'Biryani',
      image: 'assets/images/Kaju biryani.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Chicken Dum Biryani ',
      price: 380,
      category: 'Biryani',
      image: 'assets/images/Chicken Dum Biryani.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Fry Chicken Biryani ',
      price: 380,
      category: 'Biryani',
      image: 'assets/images/Fry Chicken Biryani.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Boneless Chicken Biryani ',
      price: 400,
      category: 'Biryani',
      image: 'assets/images/Boneless Chicken Biryani.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Kolkatta Chicken Biryani ',
      price: 400,
      category: 'Biryani',
      image: 'assets/images/Kolkatta Chicken Biryani.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Mutton Chicken Biryani ',
      price: 500,
      category: 'Biryani',
      image: 'assets/images/Mutton Chicken Biryani.webp',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Fish Biryani ',
      price: 500,
      category: 'Biryani',
      image: 'assets/images/Fish Biryani.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Prawn Biryani ',
      price: 500,
      category: 'Biryani',
      image: 'assets/images/Prawn Biryani.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Egg Biryani ',
      price: 310,
      category: 'Biryani',
      image: 'assets/images/Egg Biryani.webp',
      type: 'non-veg',
      selectedQty: 1,
    },
    //========================= SAMOSA =============================
    {
      name: 'Punjabi Aloo Samosa',
      price: 20,
      category: 'Samosa',
      image: 'assets/images/Punjabi Aloo Samosa.jpg',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Corn & Cheese Samosa',
      price: 53,
      category: 'Samosa',
      image: 'assets/images/Corn & Cheese Samosa.jpg',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Tandoori Paneer Tikka Samosa ',
      price: 69,
      category: 'Samosa',
      image: 'assets/images/Tandoori Paneer Tikka Samosa .webp',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Jodhpuri Aloo Pyaz Samosa',
      price: 49,
      category: 'Samosa',
      image: 'assets/images/Jodhpuri Aloo Pyaz Samosa.jpg',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Noodle Samosa',
      price: 49,
      category: 'Samosa',
      image: 'assets/images/Noodle Samosa.jpg',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Punjabi Aloo Samosa',
      price: 20,
      category: 'Samosa',
      image: 'assets/images/Punjabi Aloo Samosa.jpg',
      // type: 'veg',
      selectedQty: 1,
    },
    //========================= PASTA =============================
    {
      name: 'Spaghetti Pasta',
      price: 299,
      category: 'Pasta',
      image: 'assets/images/Spaghetti Pasta.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Penne Pasta',
      price: 199,
      category: 'Pasta',
      image: 'assets/images/Penne Pasta.png',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Lasagne Pasta',
      price: 249,
      category: 'Pasta',
      image: 'assets/images/Lasagne Pasta.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Ravioli Pasta',
      price: 600,
      category: 'Pasta  ',
      image: 'assets/images/Ravioli Pasta.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Linguine Pasta',
      price: 500,
      category: 'Pasta',
      image: 'assets/images/Linguine Pasta.webp',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Rigatoni Pasta',
      price: 400,
      category: 'Pasta  ',
      image: 'assets/images/Rigatoni Pasta.webp',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Farfalle Pasta',
      price: 350,
      category: 'Pasta',
      image: 'assets/images/Farfalle Pasta.webp',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Fusilli Pasta',
      price: 60,
      category: 'Pasta',
      image: 'assets/images/Fusilli Pasta.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Macaroni Pasta ',
      price: 200,
      category: 'Pasta',
      image: 'assets/images/Macaroni Pasta.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Cannelloni Pasta',
      price: 150,
      category: 'Pasta',
      image: 'assets/images/Cannelloni Pasta.avif',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Carbonara Chicken & Bacon Pasta ',
      price: 600,
      category: 'Pasta',
      image: 'assets/images/Carbonara Chicken & Bacon Pasta .jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Chicken Boscaiola Pasta',
      price: 1500,
      category: 'Pasta',
      image: 'assets/images/Chicken Boscaiola Pasta.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Chicken Pesto Pasta',
      price: 300,
      category: 'Pasta',
      image: 'assets/images/Chicken Pesto Pasta.webp',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Chicken Marinara Pasta',
      price: 600,
      category: 'Pasta',
      image: 'assets/images/Chicken Marinara Pasta.webp',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Chicken Bolognese Pasta',
      price: 300,
      category: 'Pasta',
      image: 'assets/images/Chicken Bolognese Pasta.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Lamb Bolognese Pasta',
      price: 400,
      category: 'Pasta',
      image: 'assets/images/Lamb Bolognese Pasta.avif',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Fungi Fettuccine Polo Pasta',
      price: 699,
      category: 'Pasta',
      image: 'assets/images/Fungi Fettuccine Polo Pasta.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    //========================= JUICE =============================
    {
      name: 'Mosambi Juice',
      price: 120,
      category: 'Juice',
      image: 'assets/images/mosambi juice.webp',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Orange juice',
      price: 145,
      category: 'Juice',
      image: 'assets/images/Orange juice.webp',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Pineapple juice',
      price: 150,
      category: 'Juice',
      image: 'assets/images/Pineapple juice.webp',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Mango juice',
      price: 150,
      category: 'Juice',
      image: 'assets/images/Mango juice.jpg',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Apple Juice',
      price: 150,
      category: 'Juice',
      image: 'assets/images/Apple juice.jpg',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Mosambi Juice',
      price: 60,
      category: 'Juice',
      image: 'assets/images/Chiku  juice.webp',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Papaya  juice',
      price: 150,
      category: 'Juice',
      image: 'assets/images/Papaya  juice.jpg',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Grape juice',
      price: 100,
      category: 'Juice',
      image: 'assets/images/Grape  juice.jpg',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Carrot juice',
      price: 160,
      category: 'Juice',
      image: 'assets/images/Carrot juice.jpg',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Anar juice',
      price: 127,
      category: 'Juice',
      image: 'assets/images/Anar juice.webp',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Sitafal juice',
      price: 90,
      category: 'Juice',
      image: 'assets/images/Sitafal juice.jpeg',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Strawberry juice',
      price: 150,
      category: 'Juice',
      image: 'assets/images/Strawberry juice.jpg',
      // type: 'non-veg',
      selectedQty: 1,
    },
    //========================= DONUT =============================
    {
      name: 'Sugar Donut',
      price: 75,
      category: 'Donut',
      image: 'assets/images/Sugar Donut.jpg',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Apple Cider Donut',
      price: 150,
      category: 'Donut',
      image: 'assets/images/Apple Cider Donut.jpg',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Bavarian Cream Donut',
      price: 119,
      category: 'Donut',
      image: 'assets/images/Bavarian Cream Donut.webp',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Bear Claw',
      price: 200,
      category: 'Donut',
      image: 'assets/images/Bear Claw.png',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Boston Cream Donut',
      price: 149,
      category: 'Donut',
      image: 'assets/images/Boston Cream Donut.webp',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Chocolate Frosted Donut',
      price: 285,
      category: 'Donut',
      image: 'assets/images/Chocolate Frosted Donut.jpg',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Jelly Donut',
      price: 50,
      category: 'Donut',
      image: 'assets/images/Jelly Donut.jpg',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Long John',
      price: 175,
      category: 'Donut',
      image: 'assets/images/Long John.jpg',
      // type: 'non-veg',
      selectedQty: 1,
    },
    //========================= FRIED RICE =============================

    {
      name: 'Veg Fried Rice',
      price: 79,
      category: 'Fried Noodle/Rice',
      image: 'assets/images/Veg Fried Rice.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Sweet Corn Fried Rice',
      price: 199,
      category: 'Fried Noodle/Rice',
      image: 'assets/images/Sweet Corn Fried Rice.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Gobi Fried Rice',
      price: 199,
      category: 'Fried Noodle/Rice',
      image: 'assets/images/Gobi Fried Rice.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Mushroom Fried Rice',
      price: 199,
      category: 'Fried Noodle/Rice',
      image: 'assets/images/Mushroom Fried Rice.webp',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Manchurian Rice',
      price: 160,
      category: 'Fried Noodle/Rice',
      image: 'assets/images/Veg Manchurian Rice.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Soyabean Fried Rice',
      price: 50,
      category: 'Fried Noodle/Rice',
      image: 'assets/images/Veg Soyabean Fried Rice.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Schezwan Fried Rice',
      price: 99,
      category: 'Fried Noodle/Rice',
      image: 'assets/images/Veg Schezwan Fried Rice.webp',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Noodle',
      price: 130,
      category: 'Fried Noodle/Rice',
      image: 'assets/images/Veg Noodle.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Panner Noodle',
      price: 140,
      category: 'Fried Noodle/Rice',
      image: 'assets/images/Panner Noodle.webp',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Schezwan Noodle',
      price: 140,
      category: 'Fried Noodle/Rice',
      image: 'assets/images/Schezwan Noodle.webp',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Chilli Garic Noodle',
      price: 140,
      category: 'Fried Noodle/Rice',
      image: 'assets/images/Chilli Garic Noodle.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Manchurian Noodle',
      price: 150,
      category: 'Fried Noodle/Rice',
      image: 'assets/images/Veg Manchurian Noodle.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Singapore Veg Noodles',
      price: 180,
      category: 'Fried Noodle/Rice',
      image: 'assets/images/Singapore Veg Noodles.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Egg Fried Rice',
      price: 99,
      category: 'Fried Noodle/Rice',
      image: 'assets/images/Veg Schezwan Fried Rice.webp.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Chicken Fried Rice',
      price: 199,
      category: 'Fried Noodle/Rice',
      image: 'assets/images/Chicken Fried Rice.png',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Special Chicken Fried Rice',
      price: 129,
      category: 'Fried Noodle/Rice',
      image: 'assets/images/Special Chicken Fried Rice.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Schezwan Chicken Fried Rice',
      price: 129,
      category: 'Fried Noodle/Rice',
      image: 'assets/images/Schezwan Chicken Fried Rice.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Chicken Noodle',
      price: 169,
      category: 'Fried Noodle/Rice',
      image: 'assets/images/Chicken Noodle.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Chicken Hakka Noodle',
      price: 149,
      category: 'Fried Noodle/Rice',
      image: 'assets/images/Chicken Hakka Noodle.jpg.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    //=================================== MOMOS ======================================
    {
      name: 'Veg Momos',
      price: 100,
      category: 'Momos',
      image: 'assets/images/Veg Momos.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Cheese Momos',
      price: 140,
      category: 'Momos',
      image: 'assets/images/Veg Cheese Momos.webp',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Schezwan Momos',
      price: 100,
      category: 'Momos',
      image: 'assets/images/Veg Schezwan Momos.png',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Schezwan Panner Momos',
      price: 150,
      category: 'Momos',
      image: 'assets/images/Veg Schezwan Panner Momos.webp',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Chilly Momos',
      price: 140,
      category: 'Momos',
      image: 'assets/images/Veg Chilly Momos.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Tandori Momos',
      price: 150,
      category: 'Momos',
      image: 'assets/images/Veg Tandori Momos.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Peri-Peri Momos',
      price: 140,
      category: 'Momos',
      image: 'assets/images/Veg Peri-Peri Momos.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Peri-Peri Cheese Momos',
      price: 110,
      category: 'Momos',
      image: 'assets/images/Veg Peri-Peri Cheese Momos.avif',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Chicken Momos',
      price: 120,
      category: 'Momos',
      image: 'assets/images/Chicken Momos.webp',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Chicken Cheese Momos',
      price: 160,
      category: 'Momos',
      image: 'assets/images/Chicken Cheese Momos.png',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Chicken Schezwan Momos',
      price: 160,
      category: 'Momos',
      image: 'assets/images/Chicken Schezwan Momos.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Chicken Chilli Momos',
      price: 160,
      category: 'Momos',
      image: 'assets/images/Chicken Chilli Momos.png',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Chicken Tandoori Momos',
      price: 170,
      category: 'Momos',
      image: 'assets/images/Chicken Tandoori Momos.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Chicken Peri Peri Momos',
      price: 120,
      category: 'Momos',
      image: 'assets/images/Chicken Peri Peri Momos.avif',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Chicken Chilli Chesse Momos',
      price: 110,
      category: 'Momos',
      image: 'assets/images/Chicken Chilli Chesse Momos.webp',
      type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Chicken Schezwan Chesse Momos',
      price: 110,
      category: 'Momos',
      image: 'assets/images/Chicken Schezwan Chesse Momos.jpg',
      type: 'non-veg',
      selectedQty: 1,
    },
    //================================ CAKE ===================================
    {
      name: 'Classic Browine Cake',
      price: 500,
      category: 'Cake',
      image: 'assets/images/Classic Browine Cake.jpg',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Nuts Brownie Cake',
      price: 600,
      category: 'Cake',
      image: 'assets/images/Nuts Brownie Cake.jpg',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Chocolate Cookies Brownie Cake',
      price: 550,
      category: 'Cake',
      image: 'assets/images/Chocolate Cookies Brownie Cake.jpg',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Chocochips Brownie Cake',
      price: 500,
      category: 'Cake',
      image: 'assets/images/Chocochips Brownie Cake.jpg.webp',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Oreo Brownie Cake',
      price: 650,
      category: 'Cake',
      image: 'assets/images/Oreo Brownie Cake.jpeg',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Kitkat Brownie Cake',
      price: 650,
      category: 'Cake',
      image: 'assets/images/Kitkat Brownie Cake.jpg',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Milk Chocolate Brownie Cake',
      price: 600,
      category: 'Cake',
      image: 'assets/images/Milk Chocolate Brownie Cake.jpg',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'White Chocolate Brownie Cake',
      price: 650,
      category: 'Cake',
      image: 'assets/images/White Chocolate Brownie Cake.webp',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Penut Brownie Cake',
      price: 650,
      category: 'Cake',
      image: 'assets/images/Penut Brownie Cake.jpg',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Lotus Biscoff Cake',
      price: 700,
      category: 'Cake',
      image: 'assets/images/Lotus Biscoff Cake.jpg',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Black Forest Cake ',
      price: 750,
      category: 'Cake',
      image: 'assets/images/Black Forest Cake .webp',
      // type: 'non-veg',
      selectedQty: 1,
    },
    {
      name: 'Blue Berry Cake',
      price: 800,
      category: 'Cake',
      image: 'assets/images/Blue Berry Cake.jpeg',
      // type: 'non-veg',
      selectedQty: 1,
    },
    //======================================== ROLLS ===================================
    {
      name: 'Aloo Fry Roll',
      price: 30,
      category: 'Rolls',
      image: 'assets/images/Aloo Fry Roll.webp',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Mix Veg Roll ',
      price: 40,
      category: 'Rolls',
      image: 'assets/images/Mix Veg Roll .jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Cheese Roll',
      price: 80,
      category: 'Rolls',
      image: 'assets/images/Veg Cheese Roll.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Panner Roll',
      price: 90,
      category: 'Rolls',
      image: 'assets/images/Veg Panner Roll.webp',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Aloo Panner Roll',
      price: 70,
      category: 'Rolls',
      image: 'assets/images/Allo Panner Roll.webp',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Cheesy Corn Roll ',
      price: 90,
      category: 'Rolls',
      image: 'assets/images/Cheesy Corn Roll .jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Panner Mayonnaise Roll',
      price: 90,
      category: 'Rolls',
      image: 'assets/images/Panner Mayonnaise Roll.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    //========================================= Sandwich ==========================================
    {
      name: 'Veg Grill Cheese Sandwich ',
      price: 110,
      category: 'Sandwich',
      image: 'assets/images/Ved Grill  Cheese Sandwich .jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Grill Cheese Peri Peri Sandwich',
      price: 110,
      category: 'Sandwich',
      image: 'assets/images/Veg Grill Cheese Peri Peri Sandwich.webp',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Grill Cheese Tandori Sandwich ',
      price: 110,
      category: 'Sandwich',
      image: 'assets/images/Veg Grill  Cheese Tandori Sandwich.webp',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Grill Cheese Chipotle Sandwich',
      price: 110,
      category: 'Sandwich',
      image: 'assets/images/Veg Grill  Cheese Chipotle Sandwich.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Grill Cheese Salsa Sandwich',
      price: 110,
      category: 'Sandwich',
      image: 'assets/images/Veg Grill  Cheese Salsa Sandwich.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Grill Cheese Jalapeno Sandwich',
      price: 110,
      category: 'Sandwich',
      image: 'assets/images/Veg Grill  Cheese Jalapeno Sandwich.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Grill Cheese Bbq Sandwich ',
      price: 110,
      category: 'Sandwich',
      image: 'assets/images/Veg Grill Cheese Bbq Sandwich.jpg.webp',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Grill Cheese Makhani Sandwich',
      price: 110,
      category: 'Sandwich',
      image: 'assets/images/Veg Grill  Cheese Makhani Sandwich.webp',
      type: 'veg',
      selectedQty: 1,
    },
    //======================================= SOUP ================================================
    {
      name: 'Veg Sweet Corn Soup',
      price: 100,
      category: 'Soup',
      image: 'assets/images/Veg Sweet Corn Soup.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Plain Sweet Corn Soup',
      price: 100,
      category: 'Soup',
      image: 'assets/images/Plain Sweet Corn Soup.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Hot & Sour Soup',
      price: 100,
      category: 'Soup',
      image: 'assets/images/Veg Hot & Sour Soup.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Tomato Soup',
      price: 100,
      category: 'Soup',
      image: 'assets/images/Tomato Soup.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Manchurian Soup',
      price: 100,
      category: 'Soup',
      image: 'assets/images/Veg Manchurian Soup.jpg',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Schezwan Soup',
      price: 100,
      category: 'Soup',
      image: 'assets/images/Veg Schezwan Soup .webp',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Mushroom Cream Soup',
      price: 100,
      category: 'Soup',
      image: 'assets/images/Mushroom Cream Soup.webp',
      type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Veg Manchow Soup',
      price: 100,
      category: 'Soup',
      image: 'assets/images/Veg Manchow Soup.webp',
      type: 'veg',
      selectedQty: 1,
    },
    //=========================================== Ice Cream ===============================================
    {
      name: 'Vanilla Ice Cream',
      price: 40,
      category: 'Ice Cream',
      image: 'assets/images/vanilla Ice Cream.jpg',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Strawberry Ice Cream',
      price: 40,
      category: 'Ice Cream',
      image: 'assets/images/Strawberry Ice Cream.jpg',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Two In One Ice Cream',
      price: 40,
      category: 'Ice Cream',
      image: 'assets/images/Two In One Ice Cream.jpg',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Chocobar Ice Cream',
      price: 45,
      category: 'Ice Cream',
      image: 'assets/images/Chocobar Ice Cream.jpg',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Tutti Frutti Ice Cream',
      price: 45,
      category: 'Ice Cream',
      image: 'assets/images/Tutti Frutti Ice Cream.webp',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Kesar Pista Ice Cream',
      price: 45,
      category: 'Ice Cream',
      image: 'assets/images/Kesar Pista Ice Cream.jpg',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Butterscotch Ice Cream',
      price: 45,
      category: 'Ice Cream',
      image: 'assets/images/Butterscotch Ice Cream.jpg',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Chocolate Ice Cream',
      price: 45,
      category: 'Ice Cream',
      image: 'assets/images/Chocolate Ice Cream.jpg',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Cassata Ice Cream',
      price: 45,
      category: 'Ice Cream',
      image: 'assets/images/Cassata Ice Cream.jpg',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Kesar Kulfi',
      price: 45,
      category: 'Ice Cream',
      image: 'assets/images/Kesar Kulfi.jpg',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Malai Kulfi',
      price: 45,
      category: 'Ice Cream',
      image: 'assets/images/Malai Kulfi.jpg',
      // type: 'veg',
      selectedQty: 1,
    },
    {
      name: 'Mango Kulfi',
      price: 45,
      category: 'Ice Cream',
      image: 'assets/images/Mango Kulfi.jpg',
      // type: 'veg',
      selectedQty: 1,
    },
    // Add more items for other categories...
  ];

  // ... your existing properties

  selectedItemIndex: number | null = null;

  constructor(
    private cartService: CartService,
    private router: Router,
    private authService: AuthService // ← injected
  ) {}
  cartItems = []; // Your cart items array

  // Method for handling "Add" button click
  addClicked(i: number): void {
    if (this.authService.isLoggedIn()) {
      // Proceed with adding the item to the cart if the user is logged in
      this.selectedItemIndex = i;
      console.log('Item added to the cart');
    } else {
      // Redirect to the login page if the user is not logged in
      console.log('User is not logged in, redirecting to login...');
      this.router.navigate(['/login']); // Ensure the route for login is correct
    }
  }
  get filteredItems() {
    return this.allItems.filter(
      (item) => item.category === this.selectedCategory
    );
  }

  // selectCategory(category: string) {
  //   this.selectedCategory = category;
  // }

  // constructor(private cartService: CartService) {}

  addToCart(item: any) {
    if (item.selectedQty && item.selectedQty > 0) {
      const cartItem = {
        name: item.name,
        price: item.price,
        quantity: item.selectedQty,
        totalAmount: item.price * item.selectedQty,
      };
      this.cartService.addItem(cartItem);
      alert(`${item.name} added to cart!`);
    } else {
      alert('Please select quantity.');
    }
  }

  // selectedItemIndex: number | null = null;

  // addClicked(index: number): void {
  //   this.selectedItemIndex = index;
  // }

  sidebarOpen = false;  // new

  // toggle sidebar on mobile
  toggleSidebar() {
    this.sidebarOpen = !this.sidebarOpen;
  }

  // select category and close sidebar on mobile
  selectCategory(category: string) {
    this.selectedCategory = category;
    this.sidebarOpen = false;
  }

}
